atlas_forge_dir: "/Volumes/neuroinformatics/neuroinformatics/atlas-forge"
species: "BlackCap"
template_name: "template_sym_res-25um_n-18"
resolution_um: 25
transform_types: ["rigid", "similarity", "affine", "nlin"]
num_iterations: 4
show_slices: [256, 184, 252]
vmin_percentile: 1
vmax_percentile: 99.9
animation_fps: [1, 2, 4, 8]
use4template_dir_suffix: "orig-asr_N4_aligned_padded_use4template"
example_subject: "sub-BC63"
