atlas_forge_dir: "/media/ceph-niu/neuroinformatics/atlas-forge"
species: "BlackCap"
template_name: "template_sym_res-50um_n-18_average-trimean"
resolution_um: 50
transform_types: ["rigid", "similarity", "affine", "nlin"]
num_iterations: 4

# All indices are for NiFTI images as output by ANTs
# Assumes orientation is ASR
show_slices: [128, 92, 122]
insets:
  tectum:
    z: 148
    y_min: 130
    x_min: 30
    size: 80
  nidopallium:
    z: 120
    y_min: 90
    x_min: 0
    size: 80
  injection:
    z: 137
    y_min: 30
    x_min: 10
    size: 80


vmin_percentile: 1
vmax_percentile: 99.9
mip_attenuation: 0.02
animation_fps: [1, 2, 4, 8]
use4template_dir_suffix: "orig-asr_N4_aligned_padded_use4template"
example_subjects: ["sub-BC71"]
